### ISSUE TITLE
Make sure control-planes are distributed to different ZONES

### ISSUE THREAD

**Issue by mcbenjemaa** [ionos-cloud/cluster-api-provider-ionoscloud#227]
**Describe the solution you'd like:**
[A clear and concise description of what you want to happen.]

Currently, the KCP references an IONOSCloudMachine which defines a `spec. availabilityZone`.
The availability zone can be set to `AUTO`, which will let IONOS cloud decide.
But might the decision be not convenient for a HA setup

**Anything else you would like to add:**
[Miscellaneous information that will assist in solving the issue.]

We need a way of distributing control-plane nodes to different zones.

#### Proposal

Add a new field `spec. availabilityZones` which is mutually exclusive with `spec. availabilityZone`.
Always `spec. availabilityZone` take precedence.

whenever `spec. availabilityZones` is set and machine type is CP, CAPIC needs to get the KCP machines and round robin the zones for each machine.

**Comment by mcbenjemaa** [comment]
**Proposal** 

the `availabilityZone` field is still taking effect.

```yaml
kind: IonosCloudMachine
apiVersion: infrastructure.cluster.x-k8s.io/v1alpha1
metadata:
  name: "test-control-plane"
spec:
      availabilityZone: AUTO
      datacenterID: <>
      numCores: 4
      memoryMB: 8192
      
```


if the User sets both `availabilityZone` and `availabilityZones,` the `availabilityZone` take precedence.

```yaml
kind: IonosCloudMachine
apiVersion: infrastructure.cluster.x-k8s.io/v1alpha1
metadata:
  name: "test-control-plane"
spec:
      availabilityZone: AUTO
      availabilityZones: ["ZONE_1", "ZONE_2", "ZONE_3"]
      datacenterID: <>
      numCores: 4
      memoryMB: 8192
      
```

Once the `availabilityZones` is set only.
The controller will check if this machine is a CP, and will distribute the zones for all CP machines,
and finally will set the selected availability zone to the field `spec.availabilityZone`

```yaml
kind: IonosCloudMachine
apiVersion: infrastructure.cluster.x-k8s.io/v1alpha1
metadata:
  name: "test-control-plane"
spec:
      availabilityZones: ["ZONE_1", "ZONE_2", "ZONE_3"]
      datacenterID: <>
      numCores: 4
      memoryMB: 8192
      
```
